language: python
python:
  - "2.7"
  - pypy
install:
  - "pip install ."
  - "pip install -r requirements-dev.txt"
script:
  - python example/example_shapes.py
  - python example/example_flow.py
  - make clean test
